sonar.projectKey=back-front-financial-app
sonar.projectName=FinanceOS
sonar.projectVersion=1.0

# Sources
sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.test.tsx,**/dist/**,**/.next/**,**/coverage/**

# TypeScript
sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info

# Tests
sonar.test.inclusions=**/*.spec.ts,**/*.test.tsx
sonar.coverage.exclusions=**/node_modules/**,**/dist/**,**/.next/**
